apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: duch4al3l-python
  janus-idp.io/tekton: duch4al3l-python
  backstage.io/kubernetes-id: duch4al3l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: duch4al3l-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
