apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: duch4al3l-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: duch4al3l-python 
  name: duch4al3l-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: duch4al3l-python 
